#!/usr/bin/env bash

die() {
	printf "%s\n" "$*" >&2
	exit 1
}

root_dir="$(git rev-parse --show-toplevel 2>/dev/null)" || die "Not in a git repository."
cd "$root_dir" || die "Failed to change to root directory."

is_new_version=0 do_tag=-1

while (($# > 0)); do
	case "$1" in
	-n | --no_tag)
		do_tag=0
		;;
	-y | --yes)
		do_tag=1
		;;
	esac
	shift
done

ver="$(git describe --tags --abbrev=0)" || die "Failed to get latest tag."

if ! git diff --quiet "$ver"..HEAD; then
	is_new_version=1
fi

new_ver="v$(semver bump patch "$ver")" || die "Failed to bump version."

semver validate "$new_ver" >/dev/null || die "New version '$new_ver' is not valid."

# Abort if any files are not committed.
if ! git diff --quiet || ! git diff --cached --quiet; then
	die "You have uncommitted changes. Please commit or stash them before bumping the version."
fi

# Verify things haven't changed.
[[ -f "global.gd" ]] || dir "Could not find global.gd in root directory."

# Replace the version with the new tag.
# shellcheck disable=SC2016
env \
	new_ver="${new_ver}" \
	perl -pi \
	-e 's/^\s*const\s+VERSION:\s*String\s*=.*/const VERSION: String = "$ENV{new_ver}"/;' \
	global.gd || die "Failed to update version."

# If there are changes, add and commit them.
if ! git diff --quiet -- global.gd; then
	printf "Updated version in %s to %s\n" "global.gd" "$new_ver"
	git add -- global.gd || die "Failed to stage version bump."
	git commit -m "Bump version to ${new_ver}" || die "Failed to commit version bump."
	is_new_version=1
fi

if ((is_new_version)); then
	if ((do_tag < 0)); then
		# Ask if it is okay to do the tag.
		read -r -p "Run 'git tag' to change $ver to $new_ver? [y/N] " response
		if [[ "$response" =~ ^[Yy] ]]; then
			do_tag=1
		else
			do_tag=0
		fi
	fi

	if ((do_tag > 0)); then
		git tag "${new_ver}"
	else
		printf "Skipping 'git tag %s'\n" "$new_ver"
	fi
else
	printf "Nothing to do. Good night.\n"
fi

# EOF
