#!/usr/bin/env bash

#MISE description="Bump the project version"
#USAGE about "Bumps the project version in global.gd and (optionally) creates a git tag."
#USAGE flag "-n --no" help="Do not ask to create a git tag for the new version"
#USAGE flag "-y --yes" help="Automatically create a git tag for the new version"
#USAGE arg "<bump>" default="patch" help="The type of version bump to perform" {
#USAGE     choices "major" "minor" "patch"
#USAGE }

set -euo pipefail

die() {
    printf "%s\n" "$*" >&2
    exit 1
}

patch_version() {
    local new_version=$1

    # shellcheck disable=SC2016
    env \
        new_version="${new_version}" \
        perl -pi \
        -e 's/^\s*const\s+VERSION:\s*String\s*=.*/const VERSION: String = "$ENV{new_version}"/;' \
        global.gd || die "Failed to update to version ${new_version}."
}

root_dir="$(git rev-parse --show-toplevel 2>/dev/null)" || die "Not in a git repository."
cd "${root_dir}" || die "Failed to change to root directory."

is_new_version=0 do_tag=-1

if [[ ${usage_no_tag-} == "true" ]]; then
    do_tag=0
elif [[ ${usage_yes-} == "true" ]]; then
    do_tag=1
else
    do_tag=-1
fi

ver="$(git describe --tags --abbrev=0)" || die "Failed to get latest tag."

if ! git diff --quiet "${ver}"..HEAD; then
    is_new_version=1
fi

new_ver="v$(semver bump patch "${ver}")" || die "Failed to bump version."

semver validate "${new_ver}" >/dev/null || die "New version '${new_ver}' is not valid."

# Abort if any files are not committed.
if ! git diff --quiet || ! git diff --cached --quiet; then
    die "You have uncommitted changes. Please commit or stash them before bumping the version."
fi

# Verify things haven't changed.
if ! [[ -f "global.gd" ]]; then
    die "Could not find global.gd in root directory."
fi

# Replace the version with the new tag.
patch_version "${new_ver}"

# If there are changes, add and commit them.
if ! git diff --quiet -- global.gd; then
    printf "Updated version in %s to %s\n" "global.gd" "${new_ver}"
    git add -- global.gd || die "Failed to stage version bump."
    git commit -m "chore: bump version to ${new_ver}" || die "Failed to commit version bump."
    is_new_version=1
fi

if ((is_new_version)); then
    if ((do_tag < 0)); then
        # Ask if it is okay to do the tag.
        read -r -p "Run 'git tag' to change ${ver} to ${new_ver}? [y/N] " response
        if [[ ${response} =~ ^[Yy] ]]; then
            do_tag=1
        else
            do_tag=0
        fi
    fi

    if ((do_tag > 0)); then
        git tag "${new_ver}"

        # Update the version to -dev after tagging.
        patch_version "${new_ver}-dev"

        # If there aren't change, complain.
        if git diff --quiet -- global.gd; then
            die "Unable to update version to ${new_ver}-dev"
        fi
        git add -- global.gd || die "Failed to stage version bump."
        git commit -m "chore: prepare for development" || die "Failed to commit version bump."
    else
        printf "Skipping 'git tag %s'\n" "${new_ver}"
    fi
else
    printf "Nothing to do. Good night.\n"
fi

# EOF
